import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://rhsso.apps.ocpuat.three.com.hk/auth/realms/crmweb/protocol/openid-connect/auth?response_type=code&client_id=crm-web&scope=openid%20email%20profile%20roles%20web-origins%20offline_access&state=UOsmYiKboRwQ-wfIZRTaO8gXh_AurRJOWtjqlbPBkkw%3D&redirect_uri=https://sales-portal-ogp-sit-crm.apps.ocpuat.three.com.hk/login/oauth2/code/oidc&nonce=DTfX-SUPCCJr25cSg_FqzTX7MLQZhd2F0jr9GOBOc34")
    page.get_by_role("textbox", name="Username or email").fill("paulhp")
    page.get_by_role("textbox", name="Username or email").press("Tab")
    page.get_by_role("textbox", name="Password").fill("#Support1001")
    page.get_by_role("button", name="Sign In").click()
    page.locator("app-new-header").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.locator("a").filter(has_text="5G HBB").click()
    page.locator("a").filter(has_text="5G BB").click()
    page.get_by_role("button", name="2").click()
    page.get_by_role("button", name="3").click()
    page.get_by_text("HPPRM00000056415G Broadband").click()
    page.locator(".pi.pi-chevron-right").click()
    page.locator("i").nth(2).click()
    page.get_by_role("textbox", name="Test ID number (override").click()
    page.get_by_role("textbox", name="Test ID number (override").fill("L893778(0)")
    page.locator("i").nth(2).click()
    page.locator("#hkIdUpload").set_input_files("image (5).png")
    page.get_by_role("button", name="Credit Check").click()
    page.locator("p-radiobutton:nth-child(3) > .p-radiobutton > .p-radiobutton-box").first.click()
    page.get_by_role("textbox", name="Contact Mobile").click()
    page.get_by_role("textbox", name="Contact Mobile").fill("62304545")
    page.get_by_role("button", name="Verify").click()
    page.locator("input[type=\"text\"]").nth(3).fill("a")
    page.locator("input[type=\"text\"]").nth(4).fill("a")
    page.locator("input[type=\"text\"]").nth(5).fill("a")
    page.locator("input[name=\"undefined\"]").click()
    page.locator("input[name=\"undefined\"]").fill("1")
    page.get_by_text("12 ON YU ROAD, ON CHUN HOUSE").click()
    page.get_by_role("textbox", name="Block").click()
    page.get_by_role("textbox", name="Block").fill("11")
    page.get_by_role("textbox", name="Floor").click()
    page.get_by_role("textbox", name="Floor").fill("11")
    page.get_by_role("textbox", name="Room").click()
    page.get_by_role("textbox", name="Room").fill("11")
    page.locator("div:nth-child(9) > .form-group > .form-field > p-radiobutton:nth-child(3) > .p-radiobutton").click()
    page.locator(".p-inputtext.p-component.p-element.form-control.credit-card-input-width").first.click()
    page.locator(".p-inputtext.p-component.p-element.form-control.credit-card-input-width").first.fill("4111")
    page.locator(".p-inputtext.p-component.p-element.form-control.credit-card-input-width.ng-untouched.ng-pristine").first.fill("1111")
    page.locator(".p-inputtext.p-component.p-element.form-control.credit-card-input-width.ng-untouched.ng-pristine").fill("1111")
    page.get_by_role("button", name="Credit Card Signature").click()
    page.get_by_role("dialog", name="Credit Card Signature").locator("canvas").click(position={"x":803,"y":177})
    page.get_by_role("button", name="Confirm").click()
    page.get_by_role("textbox", name="Name On Card").click()
    page.get_by_role("textbox", name="Name On Card").fill("11")
    page.get_by_role("textbox", name="Expiration date (MMYY)").click()
    page.get_by_role("textbox", name="Expiration date (MMYY)").fill("1339")
    page.get_by_role("textbox", name="Expiration date (MMYY)").click()
    page.get_by_role("textbox", name="Expiration date (MMYY)").fill("1239")
    page.locator("canvas").click(position={"x":769,"y":113})
    page.locator(".pi.pi-chevron-right").click()
    page.get_by_role("textbox").first.click()
    page.get_by_role("textbox").first.click()
    page.get_by_role("textbox").first.fill("898522020071811942")
    page.get_by_role("textbox").nth(1).click()
    page.get_by_role("textbox").nth(1).click()
    page.get_by_role("textbox").nth(1).fill("860756061810104")
    page.locator("i").nth(5).click()
    page.get_by_role("checkbox", name="I have read and agree to the").check()
    page.locator("canvas").click(position={"x":659,"y":84})
    page.locator("i").nth(2).click()
    page.locator("div:nth-child(2) > .p-element.ng-untouched > .p-radiobutton > .p-radiobutton-box").click()
    page.locator("i").nth(2).click()
    page.get_by_text("Primary Sim Mobile Number:").dblclick()
    page.locator("body").press("ControlOrMeta+c")
    page.get_by_role("button", name="Yes").click()
