import type {
  JourneysDocument,
  Journey,
  LocatorCatalog,
} from "../artifacts/types.js";
import { specGenerationSchema } from "../artifacts/types.js";
import { loadLlmConfigFromEnv } from "../config.js";
import { HigressClient } from "../llm/higress-client.js";
import {
  enrichPomsForJourneys,
  parsePomMethods,
  sanitizeSpecFileName,
} from "../lib/pom-utils.js";
import { readFile } from "node:fs/promises";
import path from "node:path";

export interface SpecFile {
  fileName: string;
  content: string;
  journeyId: string;
}

export interface AssistantDirectorInput {
  journeysDoc: JourneysDocument;
  catalog: LocatorCatalog;
  pomsDir: string;
  targetUrl?: string;
}

function uniquePoms(journey: Journey): string[] {
  return [...new Set(journey.steps.map((s) => s.pom))].sort();
}

function formatArgs(args: (string | number | boolean)[] | undefined): string {
  if (!args?.length) return "";
  return args
    .map((a) => (typeof a === "string" ? JSON.stringify(a) : String(a)))
    .join(", ");
}

function violatesSpecDiscipline(content: string): boolean {
  if (/page\.locator\s*\(/.test(content)) return true;
  if (/page\.\$\s*\(/.test(content)) return true;
  if (/page\.\$\$\s*\(/.test(content)) return true;
  if (/waitForTimeout\s*\(/.test(content)) return true;
  if (/['"]#[\w-]+['"]/.test(content)) return true;
  if (/xpath\s*=/i.test(content)) return true;
  return false;
}

function buildDeterministicSpec(
  journey: Journey,
  targetUrl: string,
  pomMethods: Map<string, Set<string>>,
): string {
  const poms = uniquePoms(journey);
  const imports = poms
    .map((p) => `import { ${p} } from '../poms/${p}';`)
    .join("\n");

  const varNames = new Map<string, string>();
  for (const pom of poms) {
    varNames.set(pom, pom.charAt(0).toLowerCase() + pom.slice(1));
  }

  const lines: string[] = [
    "// ============================================",
    "// Auto-generated by Assistant Director (Agent 6)",
    "// Source: journeys.json + poms/*.ts",
    "// DO NOT EDIT MANUALLY — regenerate from pipeline",
    "// ============================================",
    "",
    "import { test, expect } from '@playwright/test';",
    imports,
    "",
    `test.describe(${JSON.stringify(journey.name)}, () => {`,
  ];

  for (const pom of poms) {
    lines.push(`  let ${varNames.get(pom)}: ${pom};`);
  }

  lines.push("");
  lines.push("  test.beforeEach(async ({ page }) => {");
  for (const pom of poms) {
    const varName = varNames.get(pom)!;
    lines.push(`    ${varName} = new ${pom}(page);`);
  }
  lines.push(`    await page.goto(${JSON.stringify(targetUrl)});`);
  const primaryPom = poms[0];
  if (primaryPom) {
    const methods = pomMethods.get(primaryPom);
    if (methods?.has("waitForReady")) {
      lines.push(`    await ${varNames.get(primaryPom)}!.waitForReady();`);
    }
  }
  lines.push("  });");
  lines.push("");

  const testTitle = journey.description ?? journey.name;
  lines.push(`  test(${JSON.stringify(testTitle)}, async () => {`);

  for (const step of journey.steps) {
    const varName = varNames.get(step.pom);
    if (!varName) continue;
    const args = formatArgs(step.args);
    const comment = step.description ? `    // Step ${step.step}: ${step.description}` : `    // Step ${step.step}`;
    lines.push(comment);

    if (step.action === "navigate" && step.method === "navigateTo") {
      if (args) {
        lines.push(`    await ${varName}.${step.method}(${args});`);
      }
      continue;
    }

    if (step.method === "waitForReady") {
      lines.push(`    await ${varName}.${step.method}();`);
      continue;
    }

    lines.push(
      args
        ? `    await ${varName}.${step.method}(${args});`
        : `    await ${varName}.${step.method}();`,
    );
  }

  if (journey.expectedOutcome) {
    lines.push(`    // Expected: ${journey.expectedOutcome}`);
  }

  lines.push("    expect(true).toBeTruthy();");
  lines.push("  });");
  lines.push("});");
  lines.push("");

  return lines.join("\n");
}

async function tryLlmSpec(
  journey: Journey,
  targetUrl: string,
  pomsDir: string,
): Promise<string | null> {
  if (journey.steps.length <= 8) return null;

  const poms = uniquePoms(journey);
  const pomSnippets: Record<string, string> = {};
  for (const pom of poms) {
    try {
      pomSnippets[pom] = await readFile(path.join(pomsDir, `${pom}.ts`), "utf8");
    } catch {
      pomSnippets[pom] = "";
    }
  }

  const llm = new HigressClient(loadLlmConfigFromEnv());
  const result = await llm.chatJson(
    `Generate a Playwright test spec for one user journey. Use ONLY POM methods — no page.locator(), no CSS, no XPath, no waitForTimeout.
Import POMs from '../poms/{ClassName}'. Use test.describe + test.beforeEach + single test().
Return JSON { files: [{ fileName, content }] } with one file.`,
    JSON.stringify({ journey, targetUrl, pomSnippets }),
    specGenerationSchema,
  );

  const content = result?.files?.[0]?.content;
  if (!content || violatesSpecDiscipline(content)) return null;
  return content;
}

async function loadPomMethods(
  pomsDir: string,
  pomClasses: string[],
): Promise<Map<string, Set<string>>> {
  const map = new Map<string, Set<string>>();
  for (const pom of pomClasses) {
    try {
      const content = await readFile(path.join(pomsDir, `${pom}.ts`), "utf8");
      map.set(pom, parsePomMethods(content));
    } catch {
      map.set(pom, new Set());
    }
  }
  return map;
}

function findMissingJourneyMethods(
  journey: Journey,
  pomMethods: Map<string, Set<string>>,
): string[] {
  const missing: string[] = [];
  for (const step of journey.steps) {
    const methods = pomMethods.get(step.pom);
    if (!methods?.has(step.method)) {
      missing.push(`${step.pom}.${step.method}`);
    }
  }
  return missing;
}

function journeyMethodsSatisfied(
  journey: Journey,
  pomMethods: Map<string, Set<string>>,
): boolean {
  return findMissingJourneyMethods(journey, pomMethods).length === 0;
}

export async function runAssistantDirector(
  input: AssistantDirectorInput,
): Promise<SpecFile[]> {
  const targetUrl = input.targetUrl ?? input.journeysDoc.targetUrl ?? "/";
  const journeys = [...input.journeysDoc.journeys].sort((a, b) =>
    a.id.localeCompare(b.id),
  );

  await enrichPomsForJourneys(journeys, input.pomsDir, input.catalog);

  const allPoms = [...new Set(journeys.flatMap((j) => uniquePoms(j)))];
  const pomMethods = await loadPomMethods(input.pomsDir, allPoms);

  const specs: SpecFile[] = [];

  for (const journey of journeys) {
    let methods = pomMethods;
    if (!journeyMethodsSatisfied(journey, methods)) {
      await enrichPomsForJourneys([journey], input.pomsDir, input.catalog);
      methods = await loadPomMethods(input.pomsDir, allPoms);
    }

    let content =
      (await tryLlmSpec(journey, targetUrl, input.pomsDir)) ??
      buildDeterministicSpec(journey, targetUrl, methods);

    if (violatesSpecDiscipline(content)) {
      content = buildDeterministicSpec(journey, targetUrl, methods);
    }

    if (!journeyMethodsSatisfied(journey, methods)) {
      content = buildDeterministicSpec(journey, targetUrl, methods);
    }

    specs.push({
      fileName: sanitizeSpecFileName(journey.id),
      content,
      journeyId: journey.id,
    });
  }

  return specs;
}
